factory:
  id: factory-c
  environmentType: vm-windows
  inputModuleType: dummy
  syncProfile: test-auto
  display: true
  riskEnabled: true

namespace:
  name: aegis-spoke-system

smokeApp:
  replicas: 1
